apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  generatorPort: "5000"
  processorPort: "5001"
  viewerPort: "5002"
  processorUrl: "http://log-processor:5001"
  receiverUrl: "http://log-viewer:5002"